# Site settings
title: Clément Changeur
description: French cyberSecurity engineer website
baseurl: ""

# User settings
username: Clément Changeur
user_description: Versatile french engineer in cybersecurity, technology enthusiast, passionate about high tech achievement and novelty
user_title: CyberSecurity Engineer
email: clement@changeur.me
github_username: cchangeur

exclude: ['package.json', 'src' , 'node_modules']
