# Site settings
title: Clément Changeur
description: French cyberSecurity engineer website
baseurl: "" # "/blog" the subpath of your site, e.g. /blog/
# url: "http://localhost:3000" # the base hostname & protocol for your site

# User settings
username: Clément Changeur
user_description: Versatile french engineer in cybersecurity, technology enthusiast, passionate about high tech achievement and novelty
user_title: CyberSecurity Engineer
email: clement@changeur.me
github_username: cchangeur

# Google-analytics
google-analytics:
  id: "UA-162151508-2"

exclude: ['package.json', 'src' , 'node_modules']
